// ***************************************************************************
// preAmplify.cpp (c) 2018 Zhenhua Yu <qasim0208@163.com>
// Health Informatics Lab, Ningxia University
// All rights reserved.

#include <iostream>
#include <string>
#include <unistd.h>
#include <getopt.h>
#include <ctime>

#include "MyDefine.h"

void parseArgs(int argc, char *argv[]);
void usage(const char* app);

int main(int argc, char *argv[]) {
	/*** record elapsed time ***/
	time_t start_t, end_t;
	long time_used;
	start_t = time(NULL);
	
	parseArgs(argc, argv);
	
	/*** create thread pool ***/
	threadPool = new ThreadPool(config.getIntPara("threads"));
	threadPool->pool_init();
	
	/*** load sequence data ***/
	genome.loadRefSeq();
	
	/*** create fragments ***/
	malbac.createFrags();
	
	/*** amplify and save sequence ***/
	malbac.amplifyAndSaveProducts();
	
	end_t = time(NULL);
	time_used = end_t-start_t;
	int minutes = time_used/60;
	int seconds = time_used - minutes*60;
	cerr << "\nElapsed time: " << minutes << " minutes and " << seconds << " seconds!\n" << endl;
	
	return 0;
}

void parseArgs(int argc, char *argv[]) {
	string inputFile = "", outFile = "";
	
	int primersPerKB = 5;
	double ADOR = 0.01, FPR = 0.05;
	int threads = 1;

	struct option long_options[] = {
		{"help", no_argument, 0, 'h'},
		{"input", required_argument, 0, 'i'},
		{"primers", required_argument, 0, 'p'},
		{"ador", required_argument, 0, 'a'},
		{"fpr", required_argument, 0, 'f'},
		{"threads", required_argument, 0, 't'},
		{"output", required_argument, 0, 'o'},
		{0, 0, 0, 0}
	};

	int c;
	//Parse command line parameters
	while((c = getopt_long(argc, argv, "hi:p:a:f:t:o:", long_options, NULL)) != -1){
		switch(c){
			case 'h':
				usage(argv[0]);
				exit(0);
			case 'i':
				inputFile = optarg;
				break;
			case 'p':
				primersPerKB = atoi(optarg);
				break;
			case 'a':
				ADOR = atof(optarg);
				break;
			case 'f':
				FPR = atof(optarg);
				break;
			case 't':
				threads = atoi(optarg);
				break;
			case 'o':
				outFile = optarg;
				break;
			default :
				usage(argv[0]);
				exit(1);
		}
	}

	if(inputFile.empty()){
		cerr << "Use --input to specify the input file (fasta)." << endl;
		usage(argv[0]);
		exit(1);
	}
	
	if(outFile.empty()){
		cerr << "Use --output to specify the output file." << endl;
		usage(argv[0]);
		exit(1);
	}
	
	/*
	if(primersPerKB < 1 || primersPerKB > 15) {
		cerr << "Error: the value of parameter \"primers\" should be 1~15!" << endl;
		exit(1);
	}
	*/
	
	if(ADOR < 0 || ADOR > 0.5) {
		cerr << "Error: the value of parameter \"ador\" should be 0~0.5!" << endl;
		exit(1);
	}
	
	if(FPR < 0 || FPR > 0.5) {
		cerr << "Error: the value of parameter \"fpr\" should be 0~0.5!" << endl;
		exit(1);
	}
	
	if(threads < 1) {
		cerr << "Error: number of threads should be a positive integer!" << endl;
		exit(1);
	}
	
	config.setStringPara("ref", inputFile);
	config.setStringPara("output", outFile);
	config.setIntPara("primers", primersPerKB);
	config.setRealPara("ador", ADOR);
	config.setRealPara("fpr", FPR);
	config.setIntPara("threads", threads);
}

void usage(const char* app) {
	cerr << "\nVersion: " << current_version << endl << endl;
	cerr << "Usage: " << app << " [options]" << endl
		<< endl
		<< "Options:" << endl
		<< "    -h, --help                      give this information" << endl
		<< "    -i, --input <string>            sequence file (.fasta) generated by simuVars program" << endl
		<< "    -p, --primers <int>             average number of primers attached to 1KB-length genomic fragment during amplification [Default:5]" << endl
		<< "    -a, --ador <float>              allele dropout rate [Default:0.01]" << endl
		<< "    -f, --fpr <float>               false positive rate [Default:0.05]" << endl
		<< "    -t, --threads <int>             number of threads to use [Default:1]" << endl
		<< "    -o, --output <string>           output file to save amplification products" << endl
		<< endl
		<< "Example:" << endl
		<< "    " << app << " -i /path/to/varSimu.fa -t 5 -o /path/to/results.fa" << endl
		<< endl
		<< "Author: Zhenhua Yu <qasim0208@163.com>\n" << endl;
}

